DSO-3475: Create a job for JIRA unit test suites

diff --git a/.github/workflows/unit-test-new.yml b/.github/workflows/unit-test-new.yml
--- a/.github/workflows/unit-test-new.yml
+++ b/.github/workflows/unit-test-new.yml
@@ -1,4 +1,4 @@
-name: A new Unit Tests 
+name: New Unit Test Runner
 
 on:
   push:
@@ -151,4 +151,81 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: unit-test-report-maven-pom
+          path: unit-test-report-*
+
+  jira-unit-tests:
+    name: Run Jira Unit Tests
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Validate jfrog credential
+        run: |
+          if [[ -z "${{ secrets.JFROG_TOKEN }}" ]]; then
+            if [[ -z "${{ inputs.artifactory-username }}" ]] || [[ -z "${{ inputs.artifactory-password }}" ]]; then
+              echo [ERROR] Credential to artifactory or jfrog token must be specified.
+              exit 1
+            fi
+          fi
+        shell: bash
+
+      - name: Setup jfrog
+        uses: jfrog/setup-jfrog-cli@v4
+        env:
+          JF_ENV_1: ${{ secrets.JFROG_TOKEN }}
+
+      - name: Display jfrog setup
+          run: |
+            echo [DEBUG] Show jfrog setup
+            jfrog c show
+          shell: bash
+
+      - name: Get the latest version
+        run: |
+          cd $GITHUB_WORKSPACE
+          jfrogToken="${{ secrets.JFROG_TOKEN }}"
+          jiraUserName="${{ secrets.JIRA_USERNAME }}"
+          jiraPassword="${{ secrets.JIRA_API_TOKEN }}"
+          ./unittest-get-latest-version.sh enable-jira-versions all "${jfrogToken}" "${jiraUserName}" "${jiraPassword}"
+
+      - name: Run JIRA unit tests
+        run: |
+          cd $GITHUB_WORKSPACE
+          ./unittest-versioning-bot.sh enable-jira-versions all 
+
+      - name: Display test report
+        if: always() # Ensure this step runs even if the test script fails
+        run: |
+          cd $GITHUB_WORKSPACE
+          echo "[INFO] List the unit test report"
+          ls unit-test-report-*
+          reportFile=$(ls unit-test-report-*)
+          if [ -f "$reportFile" ]; then
+            echo "REPORT_FILE=$reportFile" >> "$GITHUB_ENV"
+            echo "## Unit Test Report"
+            cat "$reportFile"
+          else
+            echo "No unit test report file found."
+          fi
+
+      - name: Check for failures
+        if: steps.display-report.outcome == 'success' && ${{ env.REPORT_FILE }} != ''
+        run: |
+          ${{ env.ARTIFACT_BASE_NAME }}
+          failedCount=$(grep -oP 'Failed:\s+\K\d+' "${{ env.REPORT_FILE }}")
+          if [[ -n "$failedCount" && "$failedCount" -ne 0 ]]; then
+            echo "[ERROR] Unit tests failed. Found $failedCount failed test cases (threshold => 1)."
+            exit 1
+          else
+            echo "[INFO] Unit tests passed."
+          fi
+
+      - name: Upload test report as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: unit-test-report-local
           path: unit-test-report-*
